### ISSUE TITLE
Label on every page: User Guide

### ISSUE THREAD

**Issue by hanslarsson** [robovm/robovm-docs#30]
All pages in the documentation starts with the label "User guide". Is this necessary? Maybe we could add "docs" or "documentation" or "User Gudes" to the logo?
![skarmavbild 2015-04-15 kl 12 52 58](https://cloud.githubusercontent.com/assets/453051/7157290/dc169e54-e36e-11e4-9ebc-ae1fc6a77877.png)

**Comment by ajhager** [comment]
Fixed by 6c72aff2cdf10725b9b7911ead24593c67c26c9d
