### ISSUE TITLE
Tutorial Video - Using Container Views

### ISSUE THREAD

**Issue by icdmike** [robovm/robovm-docs#54]
Would you consider creating a tutorial video on how to use Container Views in a RoboVM project by embedding them into Views in a storyboard and showing how to properly add/access custom views and/or "standard" views such as "AV Player View" and "Web View"?  

This would be great because it could show how to create and manage complex UIs with RoboVM.

**Comment by ajhager** [comment]
This will be covered in my next Cross Platform video. Closing this and will track it there. #88
