### ISSUE TITLE
Enable linking to particular section in a page

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-docs#55]
Would be nice if one could get an anchor link for a section on a page in the docs, e.g. to the docs for the `<forceLinkClasses>` element in the `Configuration Reference`. Maybe an "anchor" icon could appear when hovering a section and let me right-click and `Copy link address`? Would help when answering support requests and one wants to refer to a particular section in the docs.

**Comment by ajhager** [comment]
This is a pretty simple addition.

**Comment by ajhager** [comment]
Fixed by a7b993c5b875d4daeaecb33a32402d479c9d7d10
