### ISSUE TITLE
APIs & Javadoc: API level section is incorrect

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-docs#58]
Neither Android nor we claim to support "Java API level 7". The only thing we can say about API compatibility is what we already say in the note in the beginning of the page:

```
As a general rule of thumb, if a third party library works on
Android and does not depend on Android APIs, it will work on RoboVM.
```

Android does have support for Java 7 as "language level" and we support Java 8 as the page says at the bottom.

I think the section needs to go. Sorry. :-(

**Comment by badlogic** [comment]
Removed the section.
