### ISSUE TITLE
Links to samples broken - gives 403

### ISSUE THREAD

**Issue by henricm** [robovm/robovm-docs#60]
The new fresh samples listing goes to 403 links:
Eg 
http://docs.robovm.com/Footprint

Is this known issue?

**Comment by badlogic** [comment]
Mostly just me being a dork and not fixing the Github links. Will fix tomorrow :)

**Comment by henricm** [comment]
Go to bed!!! :-)

**Comment by badlogic** [comment]
Stop posting issues at midnight :p

**Comment by henricm** [comment]
I thought I did good posting an issue instead of emailing :-)
