### ISSUE TITLE
Format menu "paths" in the text to stand out from the rest of the text

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-docs#71]
In this text the `View > Tool Windows > Gradle` references should be formatted differently compared to the rest of the text.

![screen shot 2015-06-02 at 14 12 31](https://cloud.githubusercontent.com/assets/135765/7935461/78658b34-0931-11e5-8150-0776c39cf19c.png)

**Comment by ajhager** [comment]
On top of that, all the docs need a pass to make sure the formatting for various 'names' of UI elements are consistent (menu paths, buttons, text fields, etc.) Sometimes it is plain text, other times bold or italics.

**Comment by ajhager** [comment]
Fixed by ae1dfc8a390a4556a1652f1f2254fc79eb9fc3bc
