### ISSUE TITLE
Page for RoboPods

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-docs#72]
Should include name, link to binding, link to sample, version of the sdk. 
Maybe expandable install instructions.

**Comment by badlogic** [comment]
@BlueRiverInteractive , could you provide the content in markdown. Joseph, please add it to the docs project. This essentially already exists in the RoboPods repository README. Should describe how to integrate it, and where to find the sample for the pod.

**Comment by ajhager** [comment]
Added in 2833fe54e5803307ce9307ba6514635a689c5dd6
