### ISSUE TITLE
Create "Getting started with RoboVM Studio"

### ISSUE THREAD

**Issue by badlogic** [robovm/robovm-docs#75]
- [ ] Change the guide to use RoboVM Studio
- [ ] Add small section describing how to use IntelliJ instead, but favor Studio
- [ ] Replace video

**Comment by badlogic** [comment]
Coupd just rename the IntelliJ IDEA guide and replace the video.

**Comment by ajhager** [comment]
Closed by 03498706c6375697d9f5aa710eecc835aa7707ee
