### ISSUE TITLE
Non-unique anchor names for repeated headings

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-docs#78]
On the [Configuration Reference](http://docs.robovm.com/configuration.html) page we generate anchors for _Command line usage:_ and _Example:_ headings. Since the anchor name is based on the title of the heading and these headings are repeated in every section the generated anchor names are not unique. We should either not generate anchors at all for those headings or make sure that they are unique by adding some sequence number.

![screen shot 2015-07-17 at 08 47 14](https://cloud.githubusercontent.com/assets/135765/8752469/849cf4fe-2cb4-11e5-8145-44e279f9be0a.png)

**Comment by ajhager** [comment]
Fixed by c18a119f2b3133bbb15028a03b627964725b361e
