### ISSUE TITLE
Collapsable TOC navigation items

### ISSUE THREAD

**Issue by BlueRiverInteractive** [robovm/robovm-docs#9]
The current list of navigation items is a bit heavy. I think it should only show the first level (main chapters) and expand upon clicking on them. 
If possible, something similar to https://www.parse.com/docs would be nice.

**Comment by BlueRiverInteractive** [comment]
Or such a responsive auto-highlight TOC: http://codecanyon.net/item/ubertoc-a-responsive-joomla-faq-and-toc-module/full_screen_preview/4652531 would also be nice :)

What do you think?

**Comment by ajhager** [comment]
I completely agree. The user should be able to parse the major topics at a glance.

**Comment by badlogic** [comment]
Done.
