### ISSUE TITLE
Document the process to run on device without a developer account

### ISSUE THREAD

**Issue by ntherning** [robovm/robovm-docs#91]
Since Xcode7 it is possible to develop iOS apps and debug them on device without signing up and paying for the iOS developer program. The process still involves creating a code signing certificate and a provisioning profile and an Apple ID is required:
1. Open Xcode 7, open _Xcode->Preferences->Account_, click the _+_ button in the bottom left corner , choose _Add Apple ID..._ and login using your Apple Account. This Apple ID must not be connected to a developer program (not even the Mac Developer program!).
2. Create a new iOS project using any iOS app template. The _Bundle Identifier_ MUST match the ID of your RoboVM app.
3. Click _Fix Issue_ on the General tab to create a signing identity and a provisioning profile.
4. Connect your iOS device, select it as the build destination and click the Play button to make sure the app can be launched on the device.

Steps 2-4 must be repeated for each new RoboVM app you build.

**Comment by ajhager** [comment]
Add in e099859bde8c4135f76c5ae35505048d77348ba9
